export const PLACEMENTS = [
  "Head & Face",
  "Neck",
  "Left Shoulder",
  "Right Shoulder",
  "Left Upper Arm",
  "Right Upper Arm",
  "Left Forearm",
  "Right Forearm",
  "Left Hand",
  "Right Hand",
  "Chest",
  "Sternum",
  "Ribs / Side",
  "Stomach",
  "Upper Back",
  "Lower Back",
  "Left Hip",
  "Right Hip",
  "Left Thigh",
  "Right Thigh",
  "Left Knee",
  "Right Knee",
  "Left Calf",
  "Right Calf",
  "Left Ankle",
  "Right Ankle",
  "Left Foot",
  "Right Foot",
  "Spine",
  "Full Sleeve (Left)",
  "Full Sleeve (Right)",
  "Other",
] as const;

export type Placement = typeof PLACEMENTS[number];
